//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public string Id { get; set; }

        //工号
        public Nullable<long> j_no { get; set; }

        //密码
        public string Password { get; set; }

        //管理员姓名
        public string name { get; set; }

        //联系方式
        public string tel { get; set; }
    }
}
