//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consult
    {
        public string Id { get; set; }
        public System.DateTime create_date { get; set; }
        public string Q_describe { get; set; }
        public Nullable<int> state { get; set; }
        public string A_describe { get; set; }
        public string p_id { get; set; }
        public string d_id { get; set; }
        public Nullable<int> points { get; set; }
    }
}
