//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public string Id { get; set; }
        public string d_account { get; set; }
        public string d_name { get; set; }
        public Nullable<int> d_age { get; set; }
        public string d_tel { get; set; }
        public string title { get; set; }
        public string brief { get; set; }
        public string d_sex { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string admin_id { get; set; }
        public Nullable<decimal> points { get; set; }
    }
}
