//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public string ID { get; set; }
        //患者账号
        public string p_account { get; set; }

        //患者姓名
        public string p_Name { get; set; }
        
        //身份证
        public string Idcard { get; set; }
        
        //性别
        public string p_sex { get; set; }

        public string Password { get; set; }
        
        //注册日期
        public Nullable<System.DateTime> Enroll_date { get; set; }
        
        //患者电话
        public string p_tel { get; set; }
        
        //出生日期
        public Nullable<System.DateTime> Birthday { get; set; }  
    }
}
